# Stockula Configuration - Auto-Allocation Example
# Only requires initial capital and category ratios - automatically determines optimal quantities
data:
  train_start_date: "2025-01-01"
  train_end_date: "2025-03-31"
  test_start_date: "2025-04-01"
  test_end_date: "2025-06-30"
  use_cache: true # Database caching enabled
# Portfolio configuration with automatic allocation
portfolio:
  name: "Auto-Allocated Smigula Portfolio"
  initial_capital: 20000
  allocation_method: auto
  auto_allocate: true
  allow_fractional_shares: false # Use integer shares only
  capital_utilization_target: 1.0 # Deploy all capital
  rebalance_frequency: monthly
  max_position_size: 10.0 # Allow larger positions since we have fewer stocks
  # Category-based allocation ratios (must sum to 1.0)
  category_ratios:
    INDEX: 0.35 # 35% in broad-market index funds
    MOMENTUM: 0.475 # 47.5% in momentum stocks
    SPECULATIVE: 0.175 # 17.5% in speculative plays
  # Portfolio tickers - only symbol and category required for auto-allocation
  tickers:
    # Broad-Market Core holdings (hold-only)
    - symbol: SPY
      category: INDEX
    - symbol: VOO
      category: INDEX
    - symbol: DFUSX
      category: INDEX
    - symbol: FSKAX
      category: INDEX
    - symbol: FSMDX
      category: INDEX
    - symbol: FXAIX
      category: INDEX
    # Momentum / Large-Cap Growth (tradeable)
    - symbol: NVDA
      category: MOMENTUM
      sector: Technology
    - symbol: AMD
      category: MOMENTUM
      sector: Technology
    - symbol: TSM
      category: MOMENTUM
      sector: Technology
    - symbol: AAPL
      category: MOMENTUM
      sector: Technology
    - symbol: MSFT
      category: MOMENTUM
      sector: Technology
    - symbol: GOOGL
      category: MOMENTUM
      sector: Technology
    - symbol: AMZN
      category: MOMENTUM
      sector: Consumer Cyclical
    - symbol: META
      category: MOMENTUM
      sector: Technology
    - symbol: TSLA
      category: MOMENTUM
      sector: Consumer Cyclical
    - symbol: PLTR
      category: MOMENTUM
      sector: Technology
    # Speculative High-Beta (tradeable)
    - symbol: LIDR
      category: SPECULATIVE
      sector: Technology
    - symbol: OPEN
      category: SPECULATIVE
      sector: Real Estate
    - symbol: SOFI
      category: SPECULATIVE
      sector: Financial
    - symbol: IONQ
      category: SPECULATIVE
      sector: Technology
backtest:
  # Broker configuration for realistic commission calculation
  # Available presets:
  # - robinhood: $0 commission, $0 SEC fee, TAF ($0.000166/share on sells only, waived for ≤50 shares)
  # - interactive_brokers: Tiered per-share pricing ($0.005/share, $1 minimum)
  # - td_ameritrade: $0 commission, SEC fee ($0.0000229)
  # - etrade: $0 commission, SEC fee ($0.0000229)
  # - fidelity: $0 commission, SEC fee ($0.0000229)
  # - schwab: $0 commission, SEC fee ($0.0000229)
  broker_config:
    name: "robinhood"
    # Note: Robinhood configuration as of 2024-2025:
    # - $0 commission on stocks and ETFs
    # - $0 SEC fee (as of May 14, 2024)
    # - $0.000166 per share TAF (Trading Activity Fee) on sell orders only
    # - TAF is waived for sales of 50 shares or less
    # - Maximum TAF is $8.30 per trade
    # - Options: $0.50 per contract ($0.35 with Gold subscription)
    # - Index options have additional exchange fees
  strategies:
    - name: vidya
    - name: smacross
    - name: doubleemacross
    - name: vama
    - name: er
  # Hold-only categories will not be backtested
  hold_only_categories: ["INDEX", "BOND"]
forecast:
  forecast_length: 14
  frequency: "infer" # Auto-detect frequency
  prediction_interval: 0.95 # 95% confidence interval
  model_list: "ultra_fast" # Use ultra-fast models (5-10s per symbol)
  ensemble: "simple" # simple is faster than auto
  max_generations: 1 # Reduced for speed
  num_validations: 1 # Validation splits
  max_workers: 1 # Parallel workers (reduce if still having issues)
  validation_method: "backwards" # backwards, seasonal, similarity
# Logging configuration - enable for verbose output
logging:
  enabled: true # Set to true for detailed allocation and price fetching info
  level: INFO # Logging level: DEBUG, INFO, WARNING, ERROR
  log_to_file: false # Set to true to also log to file
  log_file: "stockula.log" # Log file name
  show_allocation_details: true
  show_price_fetching: true
