# Stockula Configuration - Auto-Allocation Example
# Only requires initial capital and category ratios - automatically determines optimal quantities
data:
  # Cache settings
  use_cache: true # Database caching for faster repeated runs
  interval: "1d" # Data interval: 1d (daily), 1h (hourly), etc.
# Portfolio configuration with automatic allocation
portfolio:
  name: "Auto-Allocated Smigula Portfolio"
  initial_capital: 20000
  allocation_method: auto
  auto_allocate: true
  allow_fractional_shares: false # Use integer shares only
  capital_utilization_target: 1.0 # Deploy all capital
  rebalance_frequency: monthly
  max_position_size: 10.0 # Allow larger positions since we have fewer stocks
  # Category-based allocation ratios (must sum to 1.0)
  category_ratios:
    INDEX: 0.35 # 35% in broad-market index funds
    MOMENTUM: 0.475 # 47.5% in momentum stocks
    SPECULATIVE: 0.175 # 17.5% in speculative plays
  # Portfolio tickers - only symbol and category required for auto-allocation
  tickers:
    # Broad-Market Core holdings (hold-only)
    - symbol: SPY
      category: INDEX
    - symbol: VOO
      category: INDEX
    - symbol: DFUSX
      category: INDEX
    - symbol: FSKAX
      category: INDEX
    - symbol: FSMDX
      category: INDEX
    - symbol: FXAIX
      category: INDEX
    # Momentum / Large-Cap Growth (tradeable)
    - symbol: NVDA
      category: MOMENTUM
      sector: Technology
    - symbol: AMD
      category: MOMENTUM
      sector: Technology
    - symbol: TSM
      category: MOMENTUM
      sector: Technology
    - symbol: AAPL
      category: MOMENTUM
      sector: Technology
    - symbol: MSFT
      category: MOMENTUM
      sector: Technology
    - symbol: GOOGL
      category: MOMENTUM
      sector: Technology
    - symbol: AMZN
      category: MOMENTUM
      sector: Consumer Cyclical
    - symbol: META
      category: MOMENTUM
      sector: Technology
    - symbol: TSLA
      category: MOMENTUM
      sector: Consumer Cyclical
    - symbol: PLTR
      category: MOMENTUM
      sector: Technology
    # Speculative High-Beta (tradeable)
    - symbol: LIDR
      category: SPECULATIVE
      sector: Technology
    - symbol: OPEN
      category: SPECULATIVE
      sector: Real Estate
    - symbol: SOFI
      category: SPECULATIVE
      sector: Financial
    - symbol: IONQ
      category: SPECULATIVE
      sector: Technology
backtest:
  # Initial cash for backtesting (if different from portfolio initial_capital)
  # initial_cash: 10000

  # Backtest-specific date range
  # If not specified, will use data.start_date/end_date or all available data
  start_date: "2024-01-01"
  end_date: "2025-03-31"
  # Broker configuration for realistic commission calculation
  broker_config:
    name: "robinhood"
    # Robinhood configuration (2024-2025):
    # - $0 commission on stocks and ETFs
    # - $0 SEC fee (as of May 14, 2024)
    # - $0.000166/share TAF on sells only (waived for ≤50 shares, max $8.30)
  # Trading strategies to test
  strategies:
    - name: vidya
    - name: smacross
      parameters:
        fast_period: 10
        slow_period: 20
    - name: doubleemacross
    - name: vama
    - name: er
  # Hold-only categories will not be backtested
  hold_only_categories: ["INDEX", "BOND"]
  # Parameter optimization (when using train/test in forecast mode)
  optimize: false # Enable parameter optimization
  optimization_params: # Parameters to optimize (when optimize: true)
    smacross:
      fast_period: [5, 10, 20]
      slow_period: [20, 50, 100]
forecast:
  # Forecasting configuration
  # Option 1: Forecast a specific number of days from today
  # forecast_length: 14  # Days to forecast from today

  # Option 2: Train/test split for historical evaluation (mutually exclusive with forecast_length)
  # The model is trained on the training period and evaluated on the test period
  train_start_date: "2024-01-01"
  train_end_date: "2025-03-31"
  test_start_date: "2025-04-01"
  test_end_date: "2025-04-30" # Reduced to 30 days for better cross-validation
  # Common settings
  frequency: "infer" # Auto-detect from data
  prediction_interval: 0.95 # 95% confidence interval
  # Model settings (ultra_fast for quick results)
  model_list: "financial" # Options: ultra_fast, fast, default, all, financial
  ensemble: "simple" # Options: simple, auto
  max_generations: 1 # Reduced for speed
  num_validations: 1 # Minimal cross-validation
  max_workers: 1 # Parallel processing workers
  validation_method: "backwards" # Options: backwards, seasonal, similarity
# Output configuration
output:
  format: console # Options: console, json, csv
  results_dir: "./results" # Directory for saving results
# Logging configuration
logging:
  enabled: true
  level: INFO # Options: DEBUG, INFO, WARNING, ERROR
  log_to_file: false
  log_file: "stockula.log"
  show_allocation_details: true
  show_price_fetching: true
