# Test config for parallel progress tracking
data:
  start_date: "2025-01-01"
  end_date: "2025-07-25"
  use_cache: true

portfolio:
  name: "Progress Test Portfolio"
  initial_capital: 10000
  allocation_method: equal
  tickers:
    - symbol: AAPL
      quantity: 5
    - symbol: MSFT
      quantity: 3
    - symbol: GOOGL
      quantity: 1
    - symbol: AMZN
      quantity: 1
    - symbol: TSLA
      quantity: 2
    - symbol: NVDA
      quantity: 1

forecast:
  forecast_length: 7
  model_list: fast
  ensemble: auto
  max_generations: 2  # Fewer generations for faster testing