# Simple test config for forecast testing
data:
  start_date: "2025-01-01"
  end_date: "2025-07-25"
  use_cache: true

portfolio:
  name: "Test Portfolio"
  initial_capital: 10000
  allocation_method: equal
  tickers:
    - symbol: AAPL
      quantity: 10
    - symbol: MSFT
      quantity: 10

forecast:
  forecast_length: 7  # Only 7 days for faster testing
  model_list: fast
  ensemble: auto
  max_generations: 2  # Fewer generations for testing